"""
memory_gen.py — Takes interview data dict → generates all memory files.

For each file, Claude writes the FULL content from scratch using the
interview data as source material. This produces genuinely personalized
files, not templates with placeholders.

Files generated:
  memories/identity.md
  memories/writing_voice.md
  memories/sentiment_map.md
  memories/brand_goals.md
  memories/preferences.md
  memories/writing_learned.md          (empty, ready for session learning)
  memories/soul_map.md                 (generated by Claude from interview data)
  memories/twitter_target_list.md      (priority engagement accounts)
  memories/platforms/twitter/strategy.md
  memories/platforms/twitter/interaction_preferences.md
  memories/platforms/twitter/brand_learning.md  (empty)
  user_profile.json                    (config for patcher)
"""

import json
import os
from datetime import datetime
from pathlib import Path
import urllib.request


# ---------------------------------------------------------------------------
# Claude helper
# ---------------------------------------------------------------------------

def _claude(prompt: str, api_key: str, system: str = "", max_tokens: int = 1500) -> str:
    payload = {
        "model": "claude-opus-4-6",
        "max_tokens": max_tokens,
        "messages": [{"role": "user", "content": prompt}],
    }
    if system:
        payload["system"] = system
    req = urllib.request.Request(
        "https://api.anthropic.com/v1/messages",
        data=json.dumps(payload).encode(),
        headers={
            "Content-Type": "application/json",
            "x-api-key": api_key,
            "anthropic-version": "2023-06-01",
        },
        method="POST",
    )
    with urllib.request.urlopen(req, timeout=45) as resp:
        return json.loads(resp.read())["content"][0]["text"].strip()


# ---------------------------------------------------------------------------
# user_profile.json — compact config used by patcher + runtime
# ---------------------------------------------------------------------------

def gen_user_profile(data: dict) -> dict:
    f = data["foundation"]
    d = data["domain"]
    v = data["voice"]
    rg = data["register_goals"]

    profile = {
        "handle": f["handle"],
        "name": f["name"],
        "role": f["role"],
        "location": f["location"],
        "background": f.get("background", ""),
        "current_work": f.get("current_work", ""),
        "peers": f.get("peers", ""),
        "api_key_env": "ANTHROPIC_API_KEY",
        "twitter_goals": {
            "why": rg.get("why_twitter", ""),
            "ideal_follower": rg.get("ideal_follower", ""),
            "success_3mo": rg.get("success_3mo", ""),
            "replies_per_session": rg.get("replies_per_session", "3-5"),
        },
        "keyword_bank": d.get("keyword_bank", {}),
        "brand_pillars": d.get("brand_pillars", {}),
        "voice_summary": v.get("voice_analysis", {}).get("raw_voice_summary", ""),
        "content_skip": d.get("content_skip", ""),
        "avoid_types": rg.get("avoid_types", ""),
        "lifestyle": data.get("lifestyle", {}),
        "content_pillars": d.get("content_pillars", []),
        "target_accounts": d.get("target_accounts", []),
        "soul_map_data": data.get("soul_map_data", {}),
        "brand_positioning": rg.get("brand_positioning", ""),
        "cringe_definition": rg.get("cringe_definition", ""),
        "engagement_philosophy": rg.get("engagement_philosophy", ""),
        "created_at": datetime.now().isoformat(),
    }
    return profile


# ---------------------------------------------------------------------------
# identity.md
# ---------------------------------------------------------------------------

def gen_identity(data: dict, api_key: str) -> str:
    f = data["foundation"]
    d = data["domain"]

    prompt = f"""
Write a detailed identity.md file for a Twitter AI system's memory.
This file is the ground truth for who this person is. It's used by the AI to
write replies that are grounded in real personal and career context.

INTERVIEW DATA:
Handle: @{f['handle']}
Name: {f['name']}
Role: {f['role']}
Location: {f['location']}
Background: {f.get('background', '')}
Current work: {f.get('current_work', '')}
Expertise: {d.get('expertise', '')}
Unfair advantage: {d.get('unfair_advantage', '')}
Communities: {d.get('communities', '')}
Peers they admire: {f.get('peers', '')}

Write the file with these EXACT markdown sections:

## Core Facts
(bullet list of 8-12 concrete facts about them — role, location, what they build, background, communities)

## Your Unfair Advantage
(2-3 paragraphs about what makes their perspective unique — use their exact words where possible)

## What You're Building Right Now
(concrete description of current project/focus)

## Your Community + Positioning
(who they're in conversation with, what corner of Twitter they're in)

## Discovered Context
*Auto-enriched from reply edits — personal and career details revealed in session.*

(leave this section empty with just the header + italics note)

## Profile Sync Learnings
*Auto-synced from Twitter profile analysis.*

(leave this section empty)

## Career Profile Sync Learnings
*Auto-synced from Twitter profile analysis.*

(leave this section empty)

Write in second person ("You are...", "Your background...").
Be specific — not generic career fluff. Reference their actual words from the interview.
Start the file with: # Identity — @{f['handle']}
"""
    return _claude(prompt, api_key, max_tokens=2000)


# ---------------------------------------------------------------------------
# writing_voice.md
# ---------------------------------------------------------------------------

def gen_writing_voice(data: dict, api_key: str) -> str:
    f = data["foundation"]
    v = data["voice"]
    va = v.get("voice_analysis", {})

    sample_replies = v.get("sample_replies", {})
    sample_replies_block = "\n".join(
        f"  Reply {i+1}: \"{reply}\""
        for i, reply in enumerate(sample_replies.values())
        if reply
    ) if sample_replies else "(no sample replies provided)"

    uses_absurdist = v.get("uses_absurdist_pivot", "n")
    uses_confident = v.get("uses_confident_facts", "n")

    prompt = f"""
Write a detailed writing_voice.md file for @{f['handle']}'s Twitter AI assistant.
This is the craft guide the AI reads before generating every reply. It must be specific,
grounded in their actual writing, and actionable — not generic advice.

THEIR ACTUAL SAMPLE REPLIES (from domain-specific scenarios in the interview):
{sample_replies_block}

OWN BEST TWEETS THEY PROVIDED:
{v.get('own_best_tweets', '(none provided)')}

VOICE ANALYSIS:
{json.dumps(va, indent=2)[:1500]}

EXPLICIT PREFERENCES:
- Never say: {v.get('never_say', '')}
- Humor style: {v.get('humor', '')}
- Formality: {v.get('formality', '')}
- Emoji: {v.get('emoji', '')}
- Uses absurdist literal pivot pattern: {uses_absurdist}
- Uses authoritative-humorous factual pattern: {uses_confident}

Write the file with these EXACT sections:

# Writing Voice (@{f['handle']})

## Your Natural Voice
(3-4 sentence description of their natural voice — specific, grounded in their actual sample replies)

## What Works (from your actual writing)
(quote one of their sample replies, explain WHY it works for their voice)

## Tweet Structure

### For Replies
(their specific reply approach — how long, how they open, what they add)

### For Takes / Opinions
(their specific style for original takes)

## Voice Specifics

**Use:**
(8-10 specific things they DO naturally — from their actual replies)

**Don't use:**
(8-10 specific things they explicitly avoid or that contradict their style)

**Bot-signal phrases — never use:**
(10-12 phrases that would kill their credibility — include any from their "never say" list + generic AI tells)

## Length Rules
(specific length guidance based on their actual reply lengths)

{'## The "Absurdist Literal Pivot" Pattern' + chr(10) + "(if they use this pattern — describe their version of it specifically, with an example from their actual replies)" if "y" in uses_absurdist.lower() else ""}

{'## The "Authoritative but Humorously Factual" Pattern' + chr(10) + "(if they use this — describe their specific version, with an example from their actual replies)" if "y" in uses_confident.lower() else ""}

## Ground Opinions in Something Real
(specific guidance on anchoring their opinions — what kind of anchors work for their domain)

**Last Updated:** {datetime.now().strftime('%Y-%m-%d')}

Write in second person. Be specific — reference their ACTUAL replies as examples.
If their replies show a clear pattern, name it. This file is read by Claude before every reply.
"""
    return _claude(prompt, api_key, max_tokens=3000)


# ---------------------------------------------------------------------------
# sentiment_map.md
# ---------------------------------------------------------------------------

def gen_sentiment_map(data: dict, api_key: str) -> str:
    f = data["foundation"]
    rg = data["register_goals"]
    sentiments = rg.get("sentiments", {})

    sentiments_block = "\n".join(
        f"  {topic}: {feeling}" for topic, feeling in sentiments.items()
        if not topic.startswith("__")
    )
    extra = sentiments.get("__extra__", "")

    prompt = f"""
Write a sentiment_map.md file for @{f['handle']}'s Twitter AI system.
This file tells the AI how to calibrate emotional tone when replying to tweets
about different topics. It's read before generating each reply.

THEIR STATED FEELINGS:
{sentiments_block}
{f"Extra topics they mentioned: {extra}" if extra else ""}

For each topic they have strong feelings about, write a 2-3 sentence description of:
1. Their emotional stance (not just the label — the texture and why)
2. How to translate that stance into a Twitter reply (tone, what to avoid, what to lean into)

Then write a "## Learned Sentiment Patterns" section header (leave it empty — auto-filled later).

Format:
# Sentiment Map — @{f['handle']}
(one intro sentence about how to use this file)

## [Topic]
(2-3 sentences: their feeling + how to channel it into a reply)

[repeat for each topic]

## Learned Sentiment Patterns
*Auto-updated by the system based on your approvals and rejections.*

Write in second person. Make it actionable for the AI writing replies.
"""
    return _claude(prompt, api_key, max_tokens=2000)


# ---------------------------------------------------------------------------
# brand_goals.md
# ---------------------------------------------------------------------------

def gen_brand_goals(data: dict, api_key: str) -> str:
    f = data["foundation"]
    rg = data["register_goals"]
    d = data["domain"]

    prompt = f"""
Write a brand_goals.md file for @{f['handle']}'s Twitter AI system.
This defines what they're trying to build on Twitter and guides the AI toward
content that serves their actual goals.

INTERVIEW DATA:
Why on Twitter: {rg.get('why_twitter', '')}
Ideal follower: {rg.get('ideal_follower', '')}
Success in 3 months: {rg.get('success_3mo', '')}
Six month vision: {rg.get('six_month_vision', '')}
Domain: {d.get('topics', '')}
Communities: {d.get('communities', '')}
Hot takes: {d.get('hot_takes', '')}
Unfair advantage: {d.get('unfair_advantage', '')}
Brand positioning: {rg.get('brand_positioning', '')}
Brand pillars: {json.dumps(d.get('brand_pillars', {}), indent=2)[:600]}

Write the file with sections:
# Brand Goals — @{f['handle']}

## The North Star
(what they're building toward — specific, not "grow my audience")

## Target Audience
(specific description of who they want to reach and why)

## Brand Pillars
(the 3-5 themes they want to be known for — use their brand_pillars from interview if provided)

## Content That Serves the Goal
(what kinds of tweets/conversations they should be engaging with to reach their goal)

## What to Avoid
(content that doesn't serve the goal, or that would harm their brand)

## 3-Month Milestones
(specific measurable targets based on their stated success criteria)

Write in second person. Be specific and honest — not aspirational fluff.
"""
    return _claude(prompt, api_key, max_tokens=1500)


# ---------------------------------------------------------------------------
# preferences.md
# ---------------------------------------------------------------------------

def gen_preferences(data: dict, api_key: str) -> str:
    f = data["foundation"]
    rg = data["register_goals"]
    d = data["domain"]

    prompt = f"""
Write a preferences.md file for @{f['handle']}'s Twitter AI system.
This is the operational filter — what content to engage with, what to skip,
and what reply styles work for them.

INTERVIEW DATA:
Engagement types they want: {rg.get('engage_types', '')}
Content to avoid: {rg.get('avoid_types', '')} | {d.get('content_skip', '')}
Topics to avoid on Twitter: {rg.get('avoid_topics_on_twitter', [])}
Replies per session: {rg.get('replies_per_session', '3-5')}
Communities: {d.get('communities', '')}
Voice formality: {data['voice'].get('formality', '')}
Cringe definition: {rg.get('cringe_definition', '')}
Engagement philosophy: {rg.get('engagement_philosophy', '')}

Write with sections:
# Preferences — @{f['handle']}

## Content to Engage With
(specific tweet types, topics, and formats that they WANT to reply to)

## Content to Skip
(specific tweet types to ignore — be explicit, not vague)

## Session Settings
(replies per session, pacing, any other operational preferences)

## Reply Style Preferences
(length, tone, what they like in their replies)

## Learned Preferences
*Auto-updated by the system based on your approvals and rejections.*

Keep it concrete and actionable. This is read at the start of every session.
"""
    return _claude(prompt, api_key, max_tokens=1200)


# ---------------------------------------------------------------------------
# strategy.md — updated to use richer interview data
# ---------------------------------------------------------------------------

def gen_strategy(data: dict, api_key: str) -> str:
    f = data["foundation"]
    d = data["domain"]
    rg = data["register_goals"]
    lifestyle = data.get("lifestyle", {})
    content_pillars = d.get("content_pillars", [])
    keyword_bank = d.get("keyword_bank", {})
    target_accounts = d.get("target_accounts", [])

    pillars_json = json.dumps(content_pillars, indent=2)[:800] if content_pillars else "(not specified)"
    kb_json = json.dumps(keyword_bank, indent=2)[:2000] if keyword_bank else "(not generated)"
    targets_block = "\n".join(
        f"  @{a.get('handle','')} — {a.get('context','') or a.get('why','')}"
        for a in target_accounts[:10] if isinstance(a, dict)
    ) if target_accounts else "(none specified)"

    prompt = f"""Write a Twitter strategy file for @{f['handle']}'s AI system.

INTERVIEW DATA:
Role: {f['role']}
Location: {f.get('location', '')}
Domain: {d.get('topics', '')}
Unfair advantage: {d.get('unfair_advantage', '')}
Communities: {d.get('communities', '')}
Why Twitter: {rg.get('why_twitter', '')}
Brand positioning: {rg.get('brand_positioning', '')}
Engagement philosophy: {rg.get('engagement_philosophy', '')}
Cringe definition: {rg.get('cringe_definition', '')}

CONTENT PILLARS:
{pillars_json}

KEYWORD BANK:
{kb_json}

TARGET ACCOUNTS:
{targets_block}

LIFESTYLE (for local/personal content):
Food: {lifestyle.get('food', '')}
Sports: {lifestyle.get('sports', '')}
Travel: {lifestyle.get('travel', '')}
Local: {lifestyle.get('local_scene', '')}

Write with these EXACT sections:
# Twitter Strategy — @{f['handle']}

## Positioning
(what they stand for, their unique corner of Twitter, what they want to be known for)

## Content Pillars & Keyword Banks

For EACH content pillar from the data above, write:
### [Pillar Name]
**Locked minimum**: X queries per session (use locked_minimum from data, default 2)
**Keywords**: (pull relevant terms from the keyword_bank — 15-20 specific terms)
**Angle**: their specific POV and hot takes in this space
**Engage when**: the kinds of tweets worth replying to in this pillar

## Network Targets

### Priority Accounts
(List accounts from the target accounts data with context)

### Account Size Preference
(Their stated preference for peer-tier vs. larger accounts)

## Reply Angle Framework
(For each major content area: what's their natural reply posture — agree and add, push back with evidence, reframe, humor?)

## Engagement Philosophy
(Their stated philosophy on reach vs. relationships, take risks, what makes a reply worth posting)

## Lifestyle & Local Integration
(How personal interests integrate — what to look for, why it humanizes the brand)

## Anti-Patterns
(Specific things to NEVER do based on their cringe definition and stated avoids)
"""
    return _claude(prompt, api_key, max_tokens=4000)


# ---------------------------------------------------------------------------
# writing_learned.md — empty template, grows during sessions
# ---------------------------------------------------------------------------

def gen_writing_learned(data: dict) -> str:
    f = data["foundation"]
    return f"""# Writing Learned — @{f['handle']}

Dated rules extracted from reply edits. Each time you edit an AI draft,
the system extracts what changed and adds a rule here. This file grows
with every session and is what makes the system sound more like you over time.

---

## Learned Style Rules
*Auto-updated from your reply edits each session.*

"""


# ---------------------------------------------------------------------------
# interaction_preferences.md — empty template
# ---------------------------------------------------------------------------

def gen_interaction_preferences(data: dict) -> str:
    f = data["foundation"]
    return f"""# Interaction Preferences — @{f['handle']}

Topics and formats you've engaged with most — updated from session data.

---

## Learned Patterns
"""


# ---------------------------------------------------------------------------
# soul_map.md — generated by Claude from interview data
# ---------------------------------------------------------------------------

def gen_soul_map(data: dict, api_key: str) -> str:
    f = data["foundation"]
    soul_data = data.get("soul_map_data", {})

    if soul_data and soul_data.get("idiographic"):
        prompt = f"""Write a complete soul_map.md for @{f['handle']}'s AI system.
Use this synthesized interview data as your source. Expand each section into dense, actionable prose.

SOUL MAP DATA FROM INTERVIEW:
1. Idiographic/Unique factors: {soul_data.get('idiographic', '')}
2. Behavioral patterns: {soul_data.get('behavioral_patterns', '')}
3. Psychobiography: {soul_data.get('psychobiography', '')}
4. Functional assessment: {soul_data.get('functional_assessment', '')}
5. Communication profile: {soul_data.get('communication_profile', '')}
6. AI working guide: {soul_data.get('ai_working_guide', '')}

Format with EXACTLY these sections:
# Soul Map — @{f['handle']}

## 1. Idiographic Research — What Makes You Uniquely You
[2-4 dense paragraphs — synthesized from interview]

## 2. Single-Subject Design — Behavioral Patterns
[2-4 paragraphs — observable patterns in engagement, what they gravitate toward]

## 3. Psychobiography — Life Narrative Arc
[2-4 paragraphs — formative themes, career trajectory as narrative]

## 4. Functional Behavioral Assessment — The "Why"
[2-4 paragraphs — motivations behind behaviors and preferences]

## 5. Communication Profile
[2-4 paragraphs — CRITICAL: how to talk TO this person. What framing they respond to, what creates trust vs. dismissal, what triggers skepticism]

## 6. AI Working Guide
[2-4 paragraphs — how AI should work WITH this person. What to assume, what to always check, how to calibrate tone and stance]

## Evolution Log
*Auto-updated by soul-map --rebuild command.*

Write in second person. Every paragraph must be specific — no generic observations.
This file is read by the AI before every session to calibrate its approach."""
    else:
        # Fallback: generate from raw interview data
        v = data.get("voice", {})
        va = v.get("voice_analysis", {})
        d = data.get("domain", {})
        rg = data.get("register_goals", {})
        prompt = f"""Write a complete soul_map.md for @{f['handle']}'s AI system from this interview data.

IDENTITY:
Role: {f.get('role', '')}
Location: {f.get('location', '')}
Background: {f.get('background', '')}
Unfair advantage: {d.get('unfair_advantage', '')}

VOICE:
Tone: {va.get('tone', '')}
Voice summary: {va.get('raw_voice_summary', '')}
Avoids: {va.get('avoids', [])}

GOALS:
Why Twitter: {rg.get('why_twitter', '')}
Success vision: {rg.get('six_month_vision', rg.get('success_3mo', ''))}

Write with sections:
# Soul Map — @{f['handle']}

## 1. Idiographic Research — What Makes You Uniquely You
## 2. Single-Subject Design — Behavioral Patterns
## 3. Psychobiography — Life Narrative Arc
## 4. Functional Behavioral Assessment — The "Why"
## 5. Communication Profile
## 6. AI Working Guide
## Evolution Log
*Auto-updated by soul-map --rebuild command.*

Each section: 2-4 specific paragraphs. Second person. No generic observations."""

    return _claude(prompt, api_key, max_tokens=6000)


# ---------------------------------------------------------------------------
# twitter_target_list.md — priority engagement accounts
# ---------------------------------------------------------------------------

def gen_twitter_target_list(data: dict) -> str:
    import re as _re
    f = data["foundation"]
    domain = data.get("domain", {})
    target_accounts = domain.get("target_accounts", [])
    peers = f.get("peers", "")

    lines = [
        f"# Twitter Target List — @{f['handle']}",
        "# Pre-vetted accounts for priority engagement (+5 base weight)",
        "# Format: @handle — context",
        "",
    ]

    added = set()
    for acct in target_accounts:
        if isinstance(acct, dict):
            handle = acct.get("handle", "").lstrip("@").strip()
            context = acct.get("context") or acct.get("why", "")
        else:
            continue
        if handle and handle not in added:
            lines.append(f"@{handle} — {context}")
            added.add(handle)

    # Fall back to peers string if no target accounts
    if not added and peers:
        for peer in _re.split(r"[,;\n]", peers):
            peer = peer.strip().lstrip("@")
            if peer and peer not in added:
                lines.append(f"@{peer} — peer in their space")
                added.add(peer)

    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# brand_learning.md — empty template
# ---------------------------------------------------------------------------

def gen_brand_learning(data: dict) -> str:
    f = data["foundation"]
    return f"""# Brand Learning Log — @{f['handle']}

Auto-updated from reply engagement outcomes. Patience game —
this compounds over months, not sessions.
"""


# ---------------------------------------------------------------------------
# career.md — professional context, goals, and growth areas
# ---------------------------------------------------------------------------

def gen_career(data: dict, api_key: str) -> str:
    f = data["foundation"]
    rg = data["register_goals"]
    d = data["domain"]

    prompt = f"""
Write a career.md file for @{f['handle']}'s AI system memory.
This captures their professional context, goals, and growth trajectory.
It's used by the AI to inform career-related replies and to understand
what professional angles to bring to conversations.

INTERVIEW DATA:
Name: {f['name']}
Role: {f['role']}
Location: {f['location']}
Background: {f.get('background', '')}
Current work: {f.get('current_work', '')}
Expertise: {d.get('expertise', '')}
Unfair advantage: {d.get('unfair_advantage', '')}
Communities: {d.get('communities', '')}
Why Twitter: {rg.get('why_twitter', '')}
Success in 3 months: {rg.get('success_3mo', '')}
Ideal connections: {rg.get('ideal_follower', '')}

Write with these EXACT sections:

# Career Development & Learnings

## Current Role & Focus
(3-5 bullet points describing what they actually do day-to-day and their area of focus)

## Career Goals

### Short-term (3-6 months)
(3-4 specific goals based on their stated success criteria and Twitter goals)

### Medium-term (6-12 months)
(3-4 goals that follow naturally from their short-term path)

### Long-term (1+ years)
(2-3 big picture aspirations)

## Skills & Expertise
(bullet list of what they're genuinely skilled at — from their background and current work)

## Professional Learnings
*Auto-updated from sessions — specific things learned while building in public.*

---

Write in second person. Be specific and grounded in their actual answers — not generic career advice.
"""
    return _claude(prompt, api_key, max_tokens=1500)


# ---------------------------------------------------------------------------
# learning_journal.md — stub, updated from automated task runs
# ---------------------------------------------------------------------------

def gen_learning_journal(data: dict) -> str:
    f = data["foundation"]
    return f"""# Learning Journal — @{f['handle']}

Record of learnings from automated tasks, skill execution, and system improvements.

## System Updates

### What's Changed
*(Recent updates to skills, workflows, or configurations)*

---

## Skill Performance

### Twitter Engagement Skill
- Last run: —
- Engagement rate: —
- Posts made: —
- Learnings:

---

## Failures & Iterations

### What Didn't Work

### How We Fixed It
"""


# ---------------------------------------------------------------------------
# index.md — registry of all active memory files
# ---------------------------------------------------------------------------

def gen_index(data: dict) -> str:
    f = data["foundation"]
    return f"""# Memory Index — @{f['handle']}

Accurate registry of all active memory files. Update when files are added or removed.

---

## Active Files

### Core Identity (read first)
- **identity.md** — Ground truth: who you are, current role, discovered context, profile sync learnings.
- **soul_map.md** — Deep psychological synthesis. Rebuilt with `python run.py soul-map --rebuild`.

### Stable Reference (rarely changes)
- **writing_voice.md** — How you write: voice, patterns, structures, examples. The immutable craft guide.
- **brand_goals.md** — The north star for Twitter growth. Targets, what works, what not to do.
- **career.md** — Career goals, skills, opportunities. (Manual. Not auto-updated.)
- **twitter_target_list.md** — Pre-vetted priority accounts for engagement (+5 base weight).

### Learned (grows with every sync)
- **writing_learned.md** — Dated style rules auto-learned from reply edits. Appended each session.
- **sentiment_map.md** — Emotional response patterns: what topics trigger what reactions.
- **preferences.md** — Operational engagement filters. Auto-updated from approved/rejected content.

### Platform: Twitter (`platforms/twitter/`)
- **platforms/twitter/strategy.md** — Content pillars, who to engage, what to stop doing.
- **platforms/twitter/interaction_preferences.md** — Topics/tones you actively like + reply to.
- **platforms/twitter/brand_learning.md** — What has and hasn't worked in reply sessions. Auto-updated.

### Archive (`archive/`)
- **learning_journal.md** — Execution logs from automated tasks. Rotated periodically.
"""


# ---------------------------------------------------------------------------
# Main generator — writes all files to target_dir/memories/
# ---------------------------------------------------------------------------

def generate_all(data: dict, target_dir: Path, api_key: str):
    """
    Generate all memory files + user_profile.json into target_dir.
    target_dir should be the root of the new AI-Knowledge instance.
    """
    memories = target_dir / "memories"
    twitter_dir = memories / "platforms" / "twitter"
    twitter_dir.mkdir(parents=True, exist_ok=True)

    handle = data["foundation"]["handle"]

    steps = [
        ("user_profile.json", None, lambda: json.dumps(gen_user_profile(data), indent=2)),
        ("memories/identity.md", "Identity", lambda: gen_identity(data, api_key)),
        ("memories/writing_voice.md", "Writing voice", lambda: gen_writing_voice(data, api_key)),
        ("memories/sentiment_map.md", "Sentiment map", lambda: gen_sentiment_map(data, api_key)),
        ("memories/brand_goals.md", "Brand goals", lambda: gen_brand_goals(data, api_key)),
        ("memories/preferences.md", "Preferences", lambda: gen_preferences(data, api_key)),
        ("memories/career.md", "Career", lambda: gen_career(data, api_key)),
        ("memories/platforms/twitter/strategy.md", "Twitter strategy", lambda: gen_strategy(data, api_key)),
        ("memories/writing_learned.md", None, lambda: gen_writing_learned(data)),
        ("memories/platforms/twitter/interaction_preferences.md", None, lambda: gen_interaction_preferences(data)),
        ("memories/soul_map.md", "Soul map", lambda: gen_soul_map(data, api_key)),
        ("memories/twitter_target_list.md", "Target list", lambda: gen_twitter_target_list(data)),
        ("memories/platforms/twitter/brand_learning.md", None, lambda: gen_brand_learning(data)),
        ("memories/archive/learning_journal.md", None, lambda: gen_learning_journal(data)),
        ("memories/index.md", None, lambda: gen_index(data)),
    ]

    print("\n  Generating your memory files:")
    for rel_path, label, generator in steps:
        path = target_dir / rel_path
        path.parent.mkdir(parents=True, exist_ok=True)
        if label:
            print(f"    {label}...", end="", flush=True)
        try:
            content = generator()
            path.write_text(content, encoding="utf-8")
            if label:
                print(" done.")
        except Exception as e:
            if label:
                print(f" failed: {e}")

    print(f"\n  All files written to {target_dir}/memories/")
